package repository.loyaltyCustomerTable;

import jakarta.persistence.criteria.CriteriaBuilder;
import jakarta.persistence.criteria.CriteriaQuery;
import jakarta.persistence.criteria.Root;
import model.entity.LoyaltyCustomerEntity;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.cfg.Configuration;
import repository.ClothifyDatabase;

import java.util.List;

public class LoyaltyCustomerTable implements ClothifyDatabase<LoyaltyCustomerEntity> {

    private static final Configuration configuration = new Configuration().addAnnotatedClass(LoyaltyCustomerEntity.class).configure("hibernate.cfg.xml");
    private static SessionFactory sessionFactory = configuration.buildSessionFactory();

    @Override
    public List<LoyaltyCustomerEntity> getAllData() {
        Session session = sessionFactory.openSession();
        List<LoyaltyCustomerEntity> list = null;

        try {
            CriteriaBuilder builder = session.getCriteriaBuilder();
            CriteriaQuery<LoyaltyCustomerEntity> query = builder.createQuery(LoyaltyCustomerEntity.class);
            Root<LoyaltyCustomerEntity> root = query.from(LoyaltyCustomerEntity.class);
            query.select(root);

            list = session.createQuery(query).getResultList();
        } finally {
            session.close();
        }
        return list;
    }

    @Override
    public void insertAnItem(LoyaltyCustomerEntity customerEntity) {

        Session session = sessionFactory.openSession();
        Transaction tx = null;

        try {
            tx = session.beginTransaction();

            session.persist(customerEntity);  // INSERT query generated by Hibernate
            tx.commit();       // Changes permanently written to DB
        } catch (Exception e) {
            if (tx != null) tx.rollback(); // Undo changes if error
            e.printStackTrace();
        } finally {
            session.close();
        }
    }

    @Override
    public LoyaltyCustomerEntity getAnItem(String primaryID) {

        Session session = sessionFactory.openSession();

        return session.find(LoyaltyCustomerEntity.class, primaryID);
    }

    @Override
    public void updateAnItem(LoyaltyCustomerEntity customerEntity) {

        Session session = sessionFactory.openSession();
        Transaction tx = null;

        try {
            tx = session.beginTransaction();
            LoyaltyCustomerEntity customerEntityTemp = session.find(LoyaltyCustomerEntity.class, customerEntity.getId());
            customerEntityTemp.setEmail("newemail@example.com");
            session.merge(customerEntityTemp);
            tx.commit();
        } catch (Exception e) {
            if (tx != null) tx.rollback();
            e.printStackTrace();
        } finally {
            session.close();
        }

    }

    @Override
    public void deleteAnItem(String primaryID) {

        Session session = sessionFactory.openSession();
        Transaction tx = null;

        try {
            tx = session.beginTransaction();
            session.remove(getAnItem(primaryID));
            tx.commit();
        } catch (Exception e) {
            if (tx != null) tx.rollback();
            e.printStackTrace();
        } finally {
            session.close();
        }

    }
}
