package repository.customerTable;

import model.dto.CustomerEntity;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.cfg.Configuration;
import repository.ClothifyDatabase;

import java.util.List;

public class CustomerTable implements ClothifyDatabase<CustomerEntity> {


    @Override
    public List<CustomerEntity> getAllData() {
        return List.of();
    }

    @Override
    public void insertAnItem(CustomerEntity customerEntity) {

        SessionFactory factory = new Configuration().configure().buildSessionFactory();
        Session session = factory.openSession();
        Transaction tx = null;

        try {
            tx = session.beginTransaction();

            session.persist(customerEntity);  // INSERT query generated by Hibernate
            tx.commit();       // Changes permanently written to DB
        } catch (Exception e) {
            if (tx != null) tx.rollback(); // Undo changes if error
            e.printStackTrace();
        } finally {
            session.close();
        }

    }

    @Override
    public CustomerEntity getAnItem(String primaryID) {
        return null;
    }

    @Override
    public void updateAnItem(CustomerEntity customerEntity) {

    }

    @Override
    public void deleteAnItem(String primaryID) {

    }
}
